name: Ping Render Service

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/3 * * * *"
  workflow_dispatch: # allows manual trigger from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          echo "Pinging Render service..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://chatbot2-4ui7.onrender.com/)
          echo "HTTP Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ]; then
            echo "⚠️ Warning: Service returned $RESPONSE"
            exit 1
          fi